package com.satoripop.insurance.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GovernorateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGovernorateAllPropertiesEquals(Governorate expected, Governorate actual) {
        assertGovernorateAutoGeneratedPropertiesEquals(expected, actual);
        assertGovernorateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGovernorateAllUpdatablePropertiesEquals(Governorate expected, Governorate actual) {
        assertGovernorateUpdatableFieldsEquals(expected, actual);
        assertGovernorateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGovernorateAutoGeneratedPropertiesEquals(Governorate expected, Governorate actual) {
        assertThat(actual)
            .as("Verify Governorate auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGovernorateUpdatableFieldsEquals(Governorate expected, Governorate actual) {
        assertThat(actual)
            .as("Verify Governorate relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGovernorateUpdatableRelationshipsEquals(Governorate expected, Governorate actual) {
        // empty method
    }
}
